### ISSUE TITLE
Unable to synchronize with Trainline

### ISSUE THREAD

**Issue by dohseven** [konnectors/cozy-konnector-trainline#43]
When I trigger the konnector to Trainline, I have an error: _Un problème semble s'être produit pendant la tentative de connexion à Trainline. Merci de revérifier vos informations de compte ou de consulter notre aide en ligne._

I'm on a self-hosted Cozy:
```
ii  cozy                                         2018M2S3-1                     all          Cozy: Simple, Versatile, Yours
ii  cozy-coclyco                                 0.1.1-1                        all          Cozy: Simple, Versatile, Yours
ii  cozy-couchdb                                 2.1.1-0                        amd64        RESTful document oriented database
ii  cozy-nsjail                                  1.8-1                          amd64        A light-weight process isolation tool, making use of Linux namespaces
ii  cozy-stack                                   2018M2S3-1                     amd64        Cozy: Simple, Versatile, Yours

collect     git://github.com/cozy/cozy-collect.git#build        1.0.2-b7194db84a293afa3894657c447cadada1b7dd4b  ready

trainline       git://github.com/cozy/cozy-konnector-trainline.git#build    0.1.1-3dcbc9d3e0d13e07a5b531c72b2ecab007436f8c  ready
```

Here are the logs:
```
May  4 21:32:21 mymachine cozy[20884]: time="2018-05-04T21:32:21+02:00" level=warning msg="Use requestFactory instead of request. It will be removed in cozy-konnector-libs@4" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:21 mymachine cozy[20884]: time="2018-05-04T21:32:21+02:00" level=error msg="Could not parse stdout as JSON: \"{\\\"time\\\":\\\"2018-05-04T19:32:21.358Z\\\",\\\"type\\\":\\\"debug\\\",\\\"message\\\":{\\\"konnector\\\":\\\"trainline\\\",\\\"account\\\":\\\"e0fa5d21560802d3b619aaa494924c3d\\\",\\\"folder_to_save\\\":\\\"e0fa5d21560802d3b619aaa494923cb3\\\"},\\\"label\\\":\\\"cozyFields in fetch\\\",\\\"namespace\\\":\\\"BaseKonnector\\\"}\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:21 mymachine cozy[20884]: time="2018-05-04T21:32:21+02:00" level=error msg="Could not parse stdout as JSON: \"{\\\"time\\\":\\\"2018-05-04T19:32:21.760Z\\\",\\\"type\\\":\\\"debug\\\",\\\"message\\\":{\\\"_id\\\":\\\"e0fa5d21560802d3b619aaa494923cb3\\\",\\\"_type\\\":\\\"io.cozy.files\\\",\\\"_rev\\\":\\\"3-1645eb771640d3e5355db5f9606c7901\\\",\\\"links\\\":{\\\"self\\\":\\\"/files/e0fa5d21560802d3b619aaa494923cb3\\\"},\\\"attributes\\\":{\\\"type\\\":\\\"directory\\\",\\\"name\\\":\\\"Moi\\\",\\\"dir_id\\\":\\\"e0fa5d21560802d3b619aaa4949230f7\\\",\\\"created_at\\\":\\\"2018-02-06T21:25:16.422869485Z\\\",\\\"updated_at\\\":\\\"2018-02-06T21:25:16.422869485Z\\\",\\\"tags\\\":[],\\\"path\\\":\\\"/Administratif/Trainline/Moi\\\",\\\"referenced_by\\\":[{\\\"id\\\":\\\"io.cozy.konnectors%2Ftrainline\\\",\\\"type\\\":\\\"io.cozy.konnectors\\\"}]},\\\"relationships\\\":{\\\"contents\\\":{\\\"links\\\":{\\\"self\\\":\\\"/files/e0fa5d21560802d3b619aaa494923cb3/relationships/contents\\\"},\\\"meta\\\":{\\\"count\\\":25},\\\"data\\\":[{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49493229a\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa4949312f8\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494930c79\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494930267\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492fa41\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492f8c5\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492ed93\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492d717\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492e6c1\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492da8d\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492d5fd\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492c682\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492bc4c\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492ad34\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492acb8\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492a3b8\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494929f87\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494929dd7\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa49492942c\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494928682\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494927fab\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494925e64\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494927a31\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa494926bb8\\\",\\\"type\\\":\\\"io.cozy.files\\\"},{\\\"id\\\":\\\"4cdf3eac8f06a2a0a75f8ddb0a00a45e\\\",\\\"type\\\":\\\"io.cozy.files\\\"}]},\\\"parent\\\":{\\\"links\\\":{\\\"self\\\":\\\"/files/e0fa5d21560802d3b619aaa4949230f7\\\"},\\\"data\\\":{\\\"id\\\":\\\"e0fa5d21560802d3b619aaa4949230f7\\\",\\\"type\\\":\\\"io.cozy.files\\\"}},\\\"referenced_by\\\":{\\\"links\\\":{\\\"self\\\":\\\"/files/e0fa5d21560802d3b619aaa494923cb3/relationships/references\\\"},\\\"data\\\":[{\\\"id\\\":\\\"io.cozy.konnectors%2Ftrainline\\\",\\\"type\\\":\\\"io.cozy.konnectors\\\"}]}},\\\"isDir\\\":true},\\\"label\\\":\\\"folder details\\\",\\\"namespace\\\":\\\"BaseKonnector\\\"}\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=warning msg="Error caught by BaseKonnector" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"TypeError: Assignment to constant variable.\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at h (/usr/src/konnector/index.js:572:102512)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at /usr/src/konnector/index.js:344:150560\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at u (/usr/src/konnector/index.js:1:54817)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at Function.e.attempt.e.try (/usr/src/konnector/index.js:572:47819)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at p (/usr/src/konnector/index.js:344:150532)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at u (/usr/src/konnector/index.js:1:54817)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at M._settlePromiseFromHandler (/usr/src/konnector/index.js:572:80407)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at M._settlePromise (/usr/src/konnector/index.js:572:81207)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at M._settlePromise0 (/usr/src/konnector/index.js:572:81906)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at M._settlePromises (/usr/src/konnector/index.js:572:83233)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at M._fulfill (/usr/src/konnector/index.js:572:82276)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at Timeout._onTimeout (/usr/src/konnector/index.js:572:27130)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at ontimeout (timers.js:475:11)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at tryOnTimeout (timers.js:310:5)\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Could not parse stdout as JSON: \"    at Timer.listOnTimeout (timers.js:270:5) \\x1b[32m'unexpected error detail'\\x1b[39m\"" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Assignment to constant variable." domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=error msg="Assignment to constant variable." domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs slug=trainline worker_id=konnector/4
May  4 21:32:37 mymachine cozy[20884]: time="2018-05-04T21:32:37+02:00" level=warning msg="Error while performing job: Assignment to constant variable. (retry in 56.580189ms)" domain=mon.cozy.chez.moi job_id=ee302c278ff0a39cc9079e2cf00ea909 nspace=jobs worker_id=konnector/4
```

Should I post this on the [Cozy forum](https://forum.cozy.io/) too?

**Comment by dohseven** [comment]
Fixed by @doubleface, see [dedicated topic](https://forum.cozy.io/t/connecteur-trainline-en-erreur/5724) on Cozy forum
